# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo test > test.txt
  displayName: 'Run a multi-line script'

- task: JFrog.jfrog-artifactory-vsts-extension.artifactory-generic-upload.ArtifactoryGenericUpload@2
  displayName: 'Artifactory Build Upload'
  inputs:
    artifactoryService: 'apigatewaystagingartifactory'
#    artifactoryService: 'apigatewaystagingartifactory'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "$(System.DefaultWorkingDirectory)/test.txt",
            "target": "apigatewaystaging"
          }
        ]
      }