# Pipeline for apig staging

trigger: none

variables:
- group: wm_test_apigw_staging_common
- group: wm_test_apigw_staging_security_alias_creds_dev

pool:
  name: '$(agent_pool)'
  vmImage: '$(agent_pool_vmImage)'

# To do: Add apiProject as pipeline parameters (vs. pipeline variable)
# parameters:
# - name: apiProject
#   type: string
#   default: 'petstore'

steps:
- checkout: self
  submodules: "true"
  persistCredentials: "true"

- template: /pipelines/api-build-template.yml  # Template reference
  parameters:
    apiProject: $(apiProject)
    build_environment: $(environment_build)
    target_type: DEV
    prep_condition: ${{false}}
    test_condition: ${{false}}

- template: /pipelines/api-deploy-template.yml  # Template reference
  parameters:
    apiProject: $(apiProject)
    target_environment: $(environment_dev)
    target_type: DEV
    prep_condition: ${{false}}
    test_condition: ${{false}}