# Pipeline for apig staging

trigger: none

variables:
- group: wm_test_apigw_staging_prod_int

pool:
  name: '$(agent_pool)'
  vmImage: '$(agent_pool_vmImage)'

steps:
- checkout: self
  submodules: "true"
  persistCredentials: "true"

- template: /pipelines/api-configure-template.yml  # Template reference
  parameters:
    environment: $(environment)
    type: PROD-INT