# Pipeline for apig staging

trigger: none

# To do: Add apiProject as pipeline parameters (vs. pipeline variable)
# parameters:
# - name: apiProject
#   type: string
#   default: 'petstore'

variables:
- group: wm_test_apigw_staging_artifactory

jobs:
- job: Prepare
  variables:
  - group: wm_test_apigw_staging_build
  pool:
    name: '$(agent_pool)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - checkout: self
    submodules: "true"
    persistCredentials: "true"
  - bash: |
      echo "##vso[task.setvariable variable=variable_group_target]wm_test_apigw_staging_dev"
      echo "##vso[task.setvariable variable=variable_group_security_alias_creds_target]wm_test_apigw_staging_security_alias_creds_dev"
    condition: and(succeeded(), eq(variables['target_type'], 'DEV'))
  - bash: |
      echo "##vso[task.setvariable variable=variable_group_target]wm_test_apigw_staging_stage"
      echo "##vso[task.setvariable variable=variable_group_security_alias_creds_target]wm_test_apigw_staging_security_alias_creds_stage"
    condition: and(succeeded(), eq(variables['target_type'], 'STAGE'))
  - bash: |
      echo "##vso[task.setvariable variable=variable_group_target]wm_test_apigw_staging_prod"
      echo "##vso[task.setvariable variable=variable_group_security_alias_creds_target]wm_test_apigw_staging_security_alias_creds_prod"
    condition: and(succeeded(), eq(variables['target_type'], 'PROD'))

- job: Build
  variables:
  - group: wm_test_apigw_staging_build
  - ${{ if eq(variables['target_type'], 'DEV') }}:
    - group: wm_test_apigw_staging_security_alias_creds_dev
  - ${{ if eq(variables['target_type'], 'STAGE') }}:
    - group: wm_test_apigw_staging_security_alias_creds_stage
  - ${{ if eq(variables['target_type'], 'PROD') }}:
    - group: wm_test_apigw_staging_security_alias_creds_prod
  pool:
    name: '$(agent_pool)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - checkout: self
    submodules: "true"
    persistCredentials: "true"
  - template: /pipelines/api-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment)
      target_type: $(target_type)
      prep_condition: in(variables['target_type'], 'STAGE', 'PROD')
      test_condition: in(variables['target_type'], 'STAGE', 'PROD')
  - template: /pipelines/store-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      target_type: $(target_type)
      prep_condition: in(variables['target_type'], 'STAGE', 'PROD')
      test_condition: in(variables['target_type'], 'STAGE', 'PROD')

- job: Deploy
  variables:
  - group: wm_test_apigw_staging_stage
  - ${{ if eq(variables['target_type'], 'DEV') }}:
    - group: wm_test_apigw_staging_dev
  - ${{ if eq(variables['target_type'], 'STAGE') }}:
    - group: wm_test_apigw_staging_stage
  - ${{ if eq(variables['target_type'], 'PROD') }}:
    - group: wm_test_apigw_staging_prod
  pool:
    name: '$(agent_pool)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - template: /pipelines/retrieve-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      target_type: $(target_type)
      prep_condition: in(variables['target_type'], 'STAGE', 'PROD')
      test_condition: in(variables['target_type'], 'STAGE', 'PROD')
  - template: /pipelines/api-deploy-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      target_environment: $(environment)
      target_type: $(target_type)
      prep_condition: in(variables['target_type'], 'STAGE', 'PROD')
      test_condition: in(variables['target_type'], 'STAGE', 'PROD')
  dependsOn: Build
  condition: succeeded()