# Pipeline for apig staging

trigger: none

# To do: Add apiProject as pipeline parameters (vs. pipeline variable)
# parameters:
# - name: apiProject
#   type: string
#   default: 'petstore'

variables:
- group: wm_test_apigw_staging

jobs:
- job: Build
  pool:
    name: '$(agent_pool_build)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - checkout: self
    submodules: "true"
    persistCredentials: "true"
  - template: /pipelines/api-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment_build)
      target_environment: $(environment_dev)
      target_type: DEV
      prep_condition: ${{false}}
      test_condition: ${{false}}
  - template: /pipelines/store-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment_build)
      target_environment: $(environment_dev)
      target_type: DEV
      prep_condition: ${{false}}
      test_condition: ${{false}}

- job: Deploy
  pool:
    name: '$(agent_pool_dev)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - template: /pipelines/retrieve-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment_build)
      target_environment: $(environment_dev)
      target_type: DEV
      prep_condition: ${{false}}
      test_condition: ${{false}}
  - template: /pipelines/api-deploy-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment_build)
      target_environment: $(environment_dev)
      target_type: DEV
      prep_condition: ${{false}}
      test_condition: ${{false}}
  dependsOn: Build
  condition: succeeded()