# Pipeline for apig staging

trigger: none

# To do: Add apiProject as pipeline parameters (vs. pipeline variable)
# parameters:
# - name: apiProject
#   type: string
#   default: 'petstore'

variables:
- group: wm_test_apigw_staging

jobs:
- job: Build
  pool:
    name: '$(agent_pool_build)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - checkout: self
    submodules: "true"
    persistCredentials: "true"
  - template: /pipelines/api-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment_build)
      target_environment: $(environment_prod)
      target_type: PROD
      prep_condition: ${{true}}
      test_condition: ${{true}}
  - template: /pipelines/store-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment_build)
      target_environment: $(environment_prod)
      target_type: PROD
      prep_condition: ${{true}}
      test_condition: ${{true}}

- job: Deploy
  pool:
    name: '$(agent_pool_prod)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - template: /pipelines/retrieve-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment_build)
      target_environment: $(environment_prod)
      target_type: PROD
      prep_condition: ${{true}}
      test_condition: ${{true}}
  - template: /pipelines/api-deploy-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment_build)
      target_environment: $(environment_prod)
      target_type: PROD
      prep_condition: ${{true}}
      test_condition: ${{true}}
  dependsOn: Build
  condition: succeeded()