# Pipeline for apig staging

trigger: none

# To do: Add apiProject as pipeline parameters (vs. pipeline variable)
# parameters:
# - name: apiProject
#   type: string
#   default: 'petstore'

variables:
- group: wm_test_apigw_staging_artifactory

jobs:
- job: Build
  variables:
  - group: wm_test_apigw_staging_build
#  - group: wm_test_apigw_staging_security_alias_creds_stage_int
  pool:
    name: '$(agent_pool)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - checkout: self
    submodules: "true"
    persistCredentials: "true"
  - template: /pipelines/api-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment)
      target_type: STAGE-INT
      prep_condition: ${{true}}
      test_condition: ${{true}}
  - template: /pipelines/store-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      target_type: STAGE-INT
      prep_condition: ${{true}}
      test_condition: ${{true}}
  condition: eq(variables['useArtifactory'], 'true')

- job: Deploy
  variables:
  - group: wm_test_apigw_staging_stage_int
  pool:
    name: '$(agent_pool)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - template: /pipelines/retrieve-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      target_type: STAGE-INT
      prep_condition: ${{true}}
      test_condition: ${{true}}
  - template: /pipelines/api-deploy-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      target_environment: $(environment)
      target_type: STAGE-INT
      prep_condition: ${{true}}
      test_condition: ${{true}}
  dependsOn: Build
  condition: succeeded()
  
- job: Build_and_deploy
  variables:
  - group: wm_test_apigw_staging_common
#  - group: wm_test_apigw_staging_security_alias_creds_stage_int
  pool:
    name: '$(agent_pool)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - checkout: self
    submodules: "true"
    persistCredentials: "true"
  - template: /pipelines/api-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment_build)
      target_type: STAGE-INT
      prep_condition: ${{true}}
      test_condition: ${{true}}
  - template: /pipelines/api-deploy-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      target_environment: $(environment_stage_int)
      target_type: STAGE-INT
      prep_condition: ${{true}}
      test_condition: ${{true}}
  condition: eq(variables['useArtifactory'], 'false')