# Pipeline for apig staging

trigger: none

# To do: Add apiProject as pipeline parameters (vs. pipeline variable)
# parameters:
# - name: apiProject
#   type: string
#   default: 'petstore'

jobs:
- job: Build_and_deploy_to_STAGE
  variables:
  - group: wm_test_apigw_staging_common
  - group: wm_test_apigw_staging_security_alias_creds_stage
  pool:
    name: '$(agent_pool)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - checkout: self
    submodules: "true"
    persistCredentials: "true"
  - template: /pipelines/api-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment_build)
      target_type: STAGE
      prep_condition: ${{true}}
      test_condition: ${{true}}
  - template: /pipelines/api-deploy-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      target_environment: $(environment_stage)
      target_type: STAGE
      prep_condition: ${{true}}
      test_condition: ${{true}}

- job: Build_and_deploy_to_PROD
  variables:
  - group: wm_test_apigw_staging_common
  - group: wm_test_apigw_staging_security_alias_creds_prod
  pool:
    name: '$(agent_pool)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - checkout: self
    submodules: "true"
    persistCredentials: "true"
  - template: /pipelines/api-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment_build)
      target_type: PROD
      prep_condition: ${{true}}
      test_condition: ${{true}}
  - template: /pipelines/api-deploy-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      target_environment: $(environment_prod)
      target_type: PROD
      prep_condition: ${{true}}
      test_condition: ${{true}}
  dependsOn: Build_and_deploy_to_STAGE
  condition: succeeded()