# Pipeline for apig staging

trigger: none

# To do: Add apiProject as pipeline parameters (vs. pipeline variable)
# parameters:
# - name: apiProject
#   type: string
#   default: 'petstore'

variables:
- group: wm_test_apigw_staging_artifactory
- group: wm_test_apigw_staging_aliases

jobs:
- job: Build_and_deploy
  variables:
  - group: wm_test_apigw_staging_common
  pool:
    name: '$(agent_pool)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - checkout: self
    submodules: "true"
    persistCredentials: "true"
  - template: /pipelines/api-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment_build)
      target_type: CONFIG
      prep_condition: ${{false}}
      test_condition: ${{false}}
  - template: /pipelines/api-deploy-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      target_environment: $(environment_config)
      target_type: CONFIG
      prep_condition: ${{false}}
      test_condition: ${{false}}
  condition: eq(variables['useArtifactory'], 'false')

- job: Build
  variables:
  - group: wm_test_apigw_staging_build
  pool:
    name: '$(agent_pool)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - checkout: self
    submodules: "true"
    persistCredentials: "true"
  - template: /pipelines/api-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      build_environment: $(environment)
      target_type: CONFIG
      prep_condition: ${{false}}
      test_condition: ${{false}}
  - template: /pipelines/store-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      target_type: CONFIG
      prep_condition: ${{false}}
      test_condition: ${{false}}
  condition: eq(variables['useArtifactory'], 'true')

- job: Deploy
  variables:
  - group: wm_test_apigw_staging_config
  pool:
    name: '$(agent_pool)'
    vmImage: '$(agent_pool_vmImage)'
  steps:
  - template: /pipelines/retrieve-build-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      target_type: CONFIG
      prep_condition: ${{false}}
      test_condition: ${{false}}
  - template: /pipelines/api-deploy-template.yml  # Template reference
    parameters:
      apiProject: $(apiProject)
      target_environment: $(environment)
      target_type: CONFIG
      prep_condition: ${{false}}
      test_condition: ${{false}}
  dependsOn: Build
  condition: succeeded()