# Pipeline for apig staging

trigger: none

pool: '$(agent_pool_common)'

# To do: Add apiProject as pipeline parameters (vs. pipeline variable)
# parameters:
# - name: apiProject
#   type: string
#   default: 'petstore'

variables:
- group: wm_test_apigw_staging

steps:
- checkout: self
  submodules: "true"
  persistCredentials: "true"

- template: /pipelines/api-build-and-deploy-template.yml  # Template reference
  parameters:
    apiProject: $(apiProject)
    build_environment: $(environment_build)
    target_environment: $(environment_stage)
    target_type: STAGE
    prep_condition: ${{true}}
    test_condition: ${{true}}